<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoria_model');
    } 

    /*
     * Listing of categoria
     */
    function index()
    {
        $data['categoria'] = $this->Categoria_model->get_all_categoria();
        
        $data['_view'] = 'categoria/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new categoria
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'categoria_nombre' => $this->input->post('categoria_nombre'),
				'categoria_imagen' => $this->input->post('categoria_imagen'),
				'vistas' => $this->input->post('vistas'),
            );
            
            $categoria_id = $this->Categoria_model->add_categoria($params);
            redirect('categoria/index');
        }
        else
        {            
            $data['_view'] = 'categoria/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a categoria
     */
    function edit($categoria_id)
    {   
        // check if the categoria exists before trying to edit it
        $data['categoria'] = $this->Categoria_model->get_categoria($categoria_id);
        
        if(isset($data['categoria']['categoria_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'categoria_nombre' => $this->input->post('categoria_nombre'),
					'categoria_imagen' => $this->input->post('categoria_imagen'),
					'vistas' => $this->input->post('vistas'),
                );

                $this->Categoria_model->update_categoria($categoria_id,$params);            
                redirect('categoria/index');
            }
            else
            {
                $data['_view'] = 'categoria/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The categoria you are trying to edit does not exist.');
    } 

    /*
     * Deleting categoria
     */
    function remove($categoria_id)
    {
        $categoria = $this->Categoria_model->get_categoria($categoria_id);

        // check if the categoria exists before trying to delete it
        if(isset($categoria['categoria_id']))
        {
            $this->Categoria_model->delete_categoria($categoria_id);
            redirect('categoria/index');
        }
        else
            show_error('The categoria you are trying to delete does not exist.');
    }
    
}
