<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
        $this->load->model('Categoria_model');
        $this->load->model('Producto_model');
        $this->load->model('Slide_model');
        
    }

    function index()
    {
        $empresa_id = 1;
        $data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);
        $data['all_categoria'] = $this->Categoria_model->get_all_categoriactiva();
        $data['productos_ultimos'] = $this->Producto_model->get_productosultimos();
        $data['productos_vistos'] = $this->Producto_model->get_productosvistos();
        $data['all_slide'] = $this->Slide_model->get_all_slide();
        
        $data['_view'] = 'dashboard';
        //$this->load->view('layouts/main',$data);
        $this->load->view('web/index',$data);
    }
}
