<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galeria extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Galeria_model');
        $this->load->model('Producto_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        //if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
        if(1 == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of galeria
     */
    function index($producto_id)
    {
        if($this->acceso(4)){
            $data['galeria'] = $this->Galeria_model->get_all_galeria($producto_id);
            $data['producto'] = $this->Producto_model->get_producto($producto_id);
            $data['_view'] = 'galeria/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new galeria
     */
    function add($producto_id)
    {
        if($this->acceso(4)){
            $this->load->library('form_validation');
            /* *********************INICIO imagen***************************** */
            $foto="";
            if (!empty($_FILES['file']['name'])){
		
                        $this->load->library('image_lib');
                        $config['upload_path'] = './resources/images/galeria/';
                        $img_full_path = $config['upload_path'];

                        $config['allowed_types'] = 'gif|jpeg|jpg|png';
                        $config['image_library'] = 'gd2';
                        $config['max_size'] = 0;
                        $config['max_width'] = 7900;
                        $config['max_height'] = 7900;
                        
                        $new_name = time(); //str_replace(" ", "_", $this->input->post('proveedor_nombre'));
                        $config['file_name'] = $new_name; //.$extencion;
                        $config['file_ext_tolower'] = TRUE;

                        $this->load->library('upload', $config);
                        $this->upload->do_upload('file');

                        $img_data = $this->upload->data();
                        $extension = $img_data['file_ext'];
                        /* ********************INICIO para resize***************************** */
                        if ($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                            $conf['image_library'] = 'gd2';
                            $conf['source_image'] = $img_data['full_path'];
                            $conf['new_image'] = './resources/images/galeria/';
                            $conf['maintain_ratio'] = TRUE;
                            $conf['create_thumb'] = FALSE;
                            $conf['width'] = 800;
                            $conf['height'] = 600;
                            $this->image_lib->clear();
                            $this->image_lib->initialize($conf);
                            if(!$this->image_lib->resize()){
                                echo $this->image_lib->display_errors('','');
                            }
                        }
                        /* ********************F I N  para resize***************************** */
                        $confi['image_library'] = 'gd2';
                        $confi['source_image'] = './resources/images/galeria/'.$new_name.$extension;
                        $confi['new_image'] = './resources/images/galeria/'."thumb_".$new_name.$extension;
                        $confi['create_thumb'] = FALSE;
                        $confi['maintain_ratio'] = TRUE;
                        $confi['width'] = 50;
                        $confi['height'] = 50;

                        $this->image_lib->clear();
                        $this->image_lib->initialize($confi);
                        $this->image_lib->resize();

                        $foto = $new_name.$extension;
                    }
            /* *********************FIN imagen***************************** */
                $params = array(
                    'producto_id' => $producto_id,
                    'galeria_nombre' => $foto, //$this->input->post('galeria_nombre'),
                    'galeria_imagen' => $foto,
                );

                $galeria_id = $this->Galeria_model->add_galeria($params);
                redirect('galeria/index/'.$producto_id);
            
        }
    }  

    /*
     * Editing a galeria
     */
    function edit($estadocivil_id)
    {
        if($this->acceso(4)){
            // check if the galeria exists before trying to edit it
            $data['galeria'] = $this->Galeria_model->get_galeria($estadocivil_id);

            if(isset($data['galeria']['estadocivil_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('estadocivil_descripcion','Estadocivil Descripcion','required');
                if($this->form_validation->run())     
                {   
                    $params = array(
                        'estadocivil_descripcion' => $this->input->post('estadocivil_descripcion'),
                    );
                    $this->Galeria_model->update_galeria($estadocivil_id,$params);            
                    redirect('galeria/index');
                }
                else
                {
                    $data['_view'] = 'galeria/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The galeria you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting galeria
     */
    function remove($galeria_id, $producto_id)
    {
        if($this->acceso(4)){
            $galeria = $this->Galeria_model->get_galeria($galeria_id);
            $base_url = explode('/', base_url());
            $directorio = $_SERVER['DOCUMENT_ROOT'].'/'.$base_url[3].'/resources/images/galeria/';
            $foto1 = $galeria["galeria_imagen"];
            if(isset($foto1) && !empty($foto1)){
                if(file_exists($directorio.$foto1)){
                    unlink($directorio.$foto1);
                    //$mimagenthumb = str_replace(".", "_thumb.", $foto1);
                    $mimagenthumb = "thumb_".$foto1;
                    unlink($directorio.$mimagenthumb);
                }
            }
            if(isset($galeria['galeria_id']))
            {
                $this->Galeria_model->delete_galeria($galeria_id);
                redirect('galeria/index/'.$producto_id);
            }
            else
                show_error('The galeria you are trying to delete does not exist.');
        }
    }
    
}
