<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Web extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoria_model');
    }
    /*
     * muestra al publico lo que hay en la categoria seleccionada
     */
    public function vercategoria($categoria_id)
    {
        $this->load->model('Empresa_model');
        $empresa_id = 1;
        $data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);
        
        $data['categoria_id']  = $categoria_id;
        $data['all_categoria'] = $this->Categoria_model->get_all_categoriactiva();
        
        $this->load->model('Producto_model');
        $data['all_productocategoria'] = $this->Producto_model->get_productocategoria($categoria_id);
        //$data['_view'] = 'categoria/vercategoria';
        $this->load->view('web/vercategoria',$data);
        
    }
    /*
     * muestra al publico el detalle de un producto...
     */
    function verdetalle($producto_id)
    {
        $this->load->model('Producto_model');
        $data['producto'] = $this->Producto_model->get_productofull($producto_id);
        
        $this->load->model('Categoria_model');
        $data['all_categoria'] = $this->Categoria_model->get_all_categoriactiva();
        
        // $this->load->model('Galeria_model');
        // $data['all_galeria'] = $this->Galeria_model->get_all_galeria($producto_id);
        
        $this->load->model('Empresa_model');
        $empresa_id = 1;
        $data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);
        
        $this->load->view('web/verdetalle',$data);
        
    }
    
    /*
     * busca productos y categorias...
     */
    function buscar_productoscategorias()
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('buscar_producto','Producto','trim|required', array('required' => 'Este Campo no debe ser vacio'));

        if($this->form_validation->run())     
        {
            $this->load->model('Empresa_model');
            $empresa_id = 1;
            $data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);
        
            $data['categoria_id']  = $this->input->post('agileinfo_search');
            $data['all_categoria'] = $this->Categoria_model->get_all_categoriactiva();
            
            $buscar_producto = $this->input->post('buscar_producto');
            $categoria_id = $this->input->post('agileinfo_search');
            
            $data['all_productocategoria'] = $this->Categoria_model->buscar_productocategoria($buscar_producto, $categoria_id);
            
            $this->load->view('web/buscar_productoscategorias',$data);
        }else{
            redirect('');
        }
    }
    
    /* * incrementa en uno la visita a una categoria al hacer click * */
    function aumentar_categoria()
    {
        //if($this->acceso(31)){
            if ($this->input->is_ajax_request()){
                $categoria_id = $this->input->post('categoria_id');

                if ($categoria_id!=""){
                    
                    $estacategoria = $this->Categoria_model->get_categoria($categoria_id);
                    $num_visto = $estacategoria['categoria_visto']+1;
                    $params = array(
                        'categoria_visto' => $num_visto,
                    );
                    $this->Categoria_model->update_categoria($categoria_id,$params);
                    
                    echo json_encode("ok");
                }
                else echo json_encode(null);
            }
            else
            {                 
                show_404();
            }
        //}
    }
    /*
     * muestra contactos y mapa de ubicacion del negocio
     */
    function contacto()
    {
        $this->load->model('Empresa_model');
        $empresa_id = 1;
        $data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);
        
        $data['all_categoria'] = $this->Categoria_model->get_all_categoriactiva();
        
        $this->load->view('web/contacto',$data);
        
    }
    /*
     * Adding a new mensaje
     */
    function recibir_mensaje()
    {
        $this->load->model('Empresa_model');
        $empresa_id = 1;
        $data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);

        $this->load->library('form_validation');
        $this->form_validation->set_rules('mensaje_nombre','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
        $this->form_validation->set_rules('mensaje_email','Correo','trim|required|valid_email', array('required' => 'Este Campo no debe ser vacio'));
        $this->form_validation->set_rules('mensaje_texto','Mensaje','trim|required', array('required' => 'Este Campo no debe ser vacio'));
        if($this->form_validation->run())     
        {
            $this->load->model('Mensaje_model');
            $fecha_mensajerecibido = date('Y-m-d H:i:s');
            $estado = 3;
            $params = array(
                'estado_id' => $estado,
                'mensaje_nombre' => $this->input->post('mensaje_nombre'),
                'mensaje_email' => $this->input->post('mensaje_email'),
                'mensaje_telefono' => $this->input->post('mensaje_telefono'),
                'mensaje_texto' => $this->input->post('mensaje_texto'),
                'mensaje_fechahoraing' => $fecha_mensajerecibido,
            );

            $mensaje_id = $this->Mensaje_model->add_mensaje($params);

            $this->load->library('email');
            $micorreo = $data['empresa']['empresa_email'];
            $miempresa = $data['empresa']['empresa_nombre'];
            $this->email->from($micorreo, $miempresa);
            $this->email->to($this->input->post('mensaje_email'));
            //$this->email->cc('another@another-example.com');
            //$this->email->bcc('them@their-example.com');
            $this->email->subject('Gracias '.$this->input->post('mensaje_nombre').' por tu consulta');
            $this->email->message('<b>Gracias por escribirnos,</b> <br>Te responderemos lo mas antes posible');
            $this->email->set_mailtype('html');
            $this->email->send();

            redirect('');
        }
        else
        {
            $this->load->model('Categoria_model');
            //$this->load->model('Empresa_model');
            //$empresa_id = 1;
            $data['nom_mensaje'] = 1;
            //$data['empresa'] = $this->Empresa_model->get_this_empresa($empresa_id);

            $data['all_categoria'] = $this->Categoria_model->get_all_categoriactiva();

            $this->load->view('web/contacto',$data);
        }
    }
}
