<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria by categoria_id
     */
    function get_categoria($categoria_id)
    {
        return $this->db->get_where('categoria',array('categoria_id'=>$categoria_id))->row_array();
    }
        
    /*
     * Get all categoria
     */
    function get_all_categoria()
    {
        $this->db->select('c.*, e.estado_descripcion, e.estado_color');
        $this->db->from('categoria as c');
        $this->db->join('estado as e', 'c.estado_id = e.estado_id');
        $this->db->order_by('c.categoria_nombre', 'asc');
        $query = $this->db->get();
        return $query->result_array();
    }
    /*
     * Get all categorias activas
     */
    function get_all_categoriactiva()
    {
        $this->db->select('c.*, e.estado_descripcion, e.estado_color');
        $this->db->from('categoria as c');
        $this->db->join('estado as e', 'c.estado_id = e.estado_id');
        $this->db->where('c.estado_id', 1);
        $this->db->order_by('c.categoria_nombre', 'asc');
        $query = $this->db->get();
        return $query->result_array();
    }
    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoria
     */
    function update_categoria($categoria_id,$params)
    {
        $this->db->where('categoria_id',$categoria_id);
        return $this->db->update('categoria',$params);
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($categoria_id)
    {
        return $this->db->delete('categoria',array('categoria_id'=>$categoria_id));
    }
}
