<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria by categoria_id
     */
    function get_categoria($categoria_id)
    {
        return $this->db->get_where('categoria',array('categoria_id'=>$categoria_id))->row_array();
    }
        
    /*
     * Get all categoria
     */
    function get_all_categoria()
    {
        $this->db->order_by('categoria_id', 'desc');
        return $this->db->get('categoria')->result_array();
    }
        
    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoria
     */
    function update_categoria($categoria_id,$params)
    {
        $this->db->where('categoria_id',$categoria_id);
        return $this->db->update('categoria',$params);
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($categoria_id)
    {
        return $this->db->delete('categoria',array('categoria_id'=>$categoria_id));
    }
}
