<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by estado_id
     */
    function get_estado($estado_id)
    {
        $estado = $this->db->query("
            SELECT
                *

            FROM
                `estado`

            WHERE
                `estado_id` = ?
        ",array($estado_id))->row_array();

        return $estado;
    }
        
    /*
     * Get all estado
     */
    function get_all_estado()
    {
        $estado = $this->db->query("
            SELECT
                *

            FROM
                `estado`

            WHERE
                1 = 1

            ORDER BY `estado_id` 
        ");

        return $estado->result_array();
    }
        
    /*
     * function to add new estado
     */
    function add_estado($params)
    {
        $this->db->insert('estado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estado
     */
    function update_estado($estado_id,$params)
    {
        $this->db->where('estado_id',$estado_id);
        return $this->db->update('estado',$params);
    }
    
    /*
     * function to delete estado
     */
    function delete_estado($estado_id)
    {
        return $this->db->delete('estado',array('estado_id'=>$estado_id));
    }

    /*
     * Get estado
     */
    function get_estado_tipo($tipo){
        $estado = $this->db->query("
            SELECT
                e.*
            FROM
                estado e
            WHERE
                e.estado_tipo = ".$tipo."
            ORDER BY e.estado_descripcion
        ")->result_array();

        return $estado;
    }

    // function get_all_estado_activo_inactivo(){
    //     return $this->db->query("
    //         SELECT
    //             *
    //         FROM
    //             estado
    //     ");
    // }

}
