<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galeria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get galeria by galeria_id
     */
    function get_galeria($galeria_id)
    {
        $galeria = $this->db->query("
            SELECT
                *

            FROM
                `galeria`

            WHERE
                `galeria_id` = ?
        ",array($galeria_id))->row_array();

        return $galeria;
    }
        
    /*
     * Get all galeria
     */
    function get_all_galeria($producto_id)
    {
        $galeria = $this->db->query("
            SELECT
                *

            FROM
                `galeria`

            WHERE
                producto_id=".$producto_id."

            ORDER BY `galeria_id` DESC
        ")->result_array();

        return $galeria;
    }
        
    /*
     * function to add new galeria
     */
    function add_galeria($params)
    {
        $this->db->insert('galeria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update galeria
     */
    function update_galeria($galeria_id,$params)
    {
        $this->db->where('galeria_id',$galeria_id);
        return $this->db->update('galeria',$params);
    }
    
    /*
     * function to delete galeria
     */
    function delete_galeria($galeria_id)
    {
        return $this->db->delete('galeria',array('galeria_id'=>$galeria_id));
    }

    /*
    *  function to first image
    */
    function get_first_image($producto_id){
        $first_image = $this->db->query("
        SELECT galeria_imagen 
        FROM galeria AS g, producto AS p 
        WHERE g.producto_id = ".$producto_id." 
        LIMIT 1
        ")->result_array(); 
        return $first_image;
    }
}
