<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mensaje_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get all mensaje
     */
    function get_all_mensaje()
    {
        $mensaje = $this->db->query("
            SELECT
                m.*, e.estado_color, e.estado_descripcion
            FROM
                mensaje m
            LEFT JOIN estado e on m.estado_id = e.estado_id
            WHERE
                1 = 1
            ORDER BY m.mensaje_id DESC
        ")->result_array();

        return $mensaje;
    }
        
    /*
     * function to add new moneda
     */
    function add_mensaje($params)
    {
        $this->db->insert('mensaje',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mensaje
     */
    function update_mensaje($mensaje_id,$params)
    {
        $this->db->where('mensaje_id',$mensaje_id);
        return $this->db->update('mensaje',$params);
    }
    /*
     * Funcion que busca mensajes
     */
    function get_busqueda_mensaje_parametro($parametro, $limite, $elestado)
    {
        $sql = "SELECT
                m.*, e.estado_color, e.estado_descripcion

            FROM
                mensaje m
            LEFT JOIN estado e on m.estado_id = e.estado_id
            WHERE
                m.estado_id = e.estado_id
                and(m.mensaje_nombre like '%".$parametro."%' or m.mensaje_email like '%".$parametro."%'
                   or m.mensaje_telefono like '%".$parametro."%' or m.mensaje_texto like '%".$parametro."%')
                ".$elestado."
                
            GROUP BY
                m.mensaje_id
              ORDER By m.mensaje_id DESC ".$limite;

        $mensaje = $this->db->query($sql)->result_array();
        return $mensaje;
    }
    /* *****Devuelve el mensaje en un row********* */
    function get_this_mensaje($mensaje_id)
    {
        $mensaje = $this->db->query("
            SELECT
                m.*
            FROM
                mensaje m
            WHERE
                m.mensaje_id = $mensaje_id
                ")->row_array();
        return $mensaje;
    }
}
